# Generated by Django 4.2.4 on 2023-12-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracticeLog',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='exercises',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
