# Generated by Django 4.2.4 on 2023-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('minutes_practiced', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
