# Generated by Django 4.2.4 on 2023-09-11 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0002_routine"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Routine",
            new_name="Routines",
        ),
    ]
