# Generated by Django 4.2.4 on 2023-10-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0003_rename_routine_routines"),
    ]

    operations = [
        migrations.AddField(
            model_name="routines",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="routines",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="routines",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
