# Generated by Django 4.2.4 on 2023-10-03 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0004_routines_description_routines_link_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Routines",
            new_name="Routine",
        ),
    ]
