# Generated by Django 4.2.4 on 2023-10-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0005_rename_routines_routine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("time", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="routine",
            name="description",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="link",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="name",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="time",
        ),
        migrations.AddField(
            model_name="routine",
            name="routine_name",
            field=models.CharField(default="Routine", max_length=200),
        ),
        migrations.AddField(
            model_name="routine",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habit_tracker.exercise",
            ),
        ),
    ]
