# Generated by Django 4.2.4 on 2023-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0008_remove_routine_exercise_routine_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("time", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="routine",
            name="description",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="exercise_name",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="link",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="time",
        ),
        migrations.AddField(
            model_name="routine",
            name="exercise",
            field=models.ManyToManyField(
                blank=True, null=True, to="habit_tracker.exercise"
            ),
        ),
    ]
