# Generated by Django 4.2.4 on 2023-10-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0009_exercise_remove_routine_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="routine_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
