# Generated by Django 4.2.4 on 2023-10-24 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0010_alter_routine_routine_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="name",
            new_name="exercise_name",
        ),
    ]
