# Generated by Django 4.2.4 on 2023-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0012_remove_routine_exercise_exercise_routine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="routine_name",
            field=models.CharField(default="1", max_length=200),
        ),
    ]
