# Generated by Django 4.2.4 on 2023-10-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0013_alter_routine_routine_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="routine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="habit_tracker.routine",
            ),
        ),
        migrations.AlterField(
            model_name="routine",
            name="routine_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
