# Generated by Django 4.2.4 on 2023-10-27 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0014_alter_exercise_routine_alter_routine_routine_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="routine",
        ),
    ]
