# Generated by Django 4.2.4 on 2023-10-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0018_remove_routine_routine_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="exercise",
            field=models.ManyToManyField(
                blank=True, null=True, to="habit_tracker.exercise"
            ),
        ),
        migrations.AddField(
            model_name="routine",
            name="routine_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
