# Generated by Django 4.2.4 on 2023-10-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0019_routine_exercise_routine_routine_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="exercise",
            field=models.ManyToManyField(blank=True, to="habit_tracker.exercise"),
        ),
    ]
