# Generated by Django 4.2.4 on 2023-11-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0021_rename_exercise_routine_exercises"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
