# Generated by Django 4.2.4 on 2023-11-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0022_alter_exercise_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="time",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
