# Generated by Django 4.2.4 on 2023-11-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0025_alter_exercise_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="time",
            field=models.CharField(default="5 min", max_length=10),
        ),
    ]
