# Generated by Django 4.2.4 on 2023-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0026_alter_exercise_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
