# Generated by Django 4.2.4 on 2024-01-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0028_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
