# Generated by Django 4.2.4 on 2024-02-11 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0029_alter_exercise_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
